// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD05OAggAOlEnfkl3IH0EvhHdxr93v98BM',
    appId: '1:402664615612:web:2886be71ecb3313a55aab9',
    messagingSenderId: '402664615612',
    projectId: 'todo-new-98',
    authDomain: 'todo-new-98.firebaseapp.com',
    storageBucket: 'todo-new-98.appspot.com',
    measurementId: 'G-WP0J3YZ8FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI_eXrXBEChVjX-aKLYijBadsrTf0WkYs',
    appId: '1:402664615612:android:be117b29317e799e55aab9',
    messagingSenderId: '402664615612',
    projectId: 'todo-new-98',
    storageBucket: 'todo-new-98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsVsWNfesZgx38IYGu2rAD9i5UpluSALk',
    appId: '1:402664615612:ios:f142c2dbd068704755aab9',
    messagingSenderId: '402664615612',
    projectId: 'todo-new-98',
    storageBucket: 'todo-new-98.appspot.com',
    iosBundleId: 'com.example.todonew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsVsWNfesZgx38IYGu2rAD9i5UpluSALk',
    appId: '1:402664615612:ios:f142c2dbd068704755aab9',
    messagingSenderId: '402664615612',
    projectId: 'todo-new-98',
    storageBucket: 'todo-new-98.appspot.com',
    iosBundleId: 'com.example.todonew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD05OAggAOlEnfkl3IH0EvhHdxr93v98BM',
    appId: '1:402664615612:web:68794cd719c947f155aab9',
    messagingSenderId: '402664615612',
    projectId: 'todo-new-98',
    authDomain: 'todo-new-98.firebaseapp.com',
    storageBucket: 'todo-new-98.appspot.com',
    measurementId: 'G-V8B4XX3KVX',
  );

}